/* tslint:disable */
/* eslint-disable */

/**
 * AUTO-GENERATED FILE - DO NOT EDIT!
 *
 * This file was automatically generated by pg-to-ts v.4.1.1
 * $ pg-to-ts generate -c postgresql://username:password@127.0.0.1:54322/postgres -t pgmigrations -s public
 *
 */

export type Json = unknown

// Table pgmigrations
export interface Pgmigrations {
  id: number
  name: string
  run_on: Date
}
export interface PgmigrationsInput {
  id?: number
  name: string
  run_on: Date
}
const pgmigrations = {
  tableName: 'pgmigrations',
  columns: ['id', 'name', 'run_on'],
  requiredForInsert: ['name', 'run_on'],
  primaryKey: 'id',
  foreignKeys: {},
  $type: null as unknown as Pgmigrations,
  $input: null as unknown as PgmigrationsInput,
} as const

export interface TableTypes {
  pgmigrations: {
    select: Pgmigrations
    input: PgmigrationsInput
  }
}

export const tables = {
  pgmigrations,
}
