/* tslint:disable */
/* eslint-disable */

/**
 * AUTO-GENERATED FILE - DO NOT EDIT!
 *
 * This file was automatically generated by pg-to-ts v.4.1.1
 * $ pg-to-ts generate -c postgresql://username:password@127.0.0.1:54322/postgres -t language -t node -t node_attribute -t node_data_api -t node_data_binding -t node_plugin -t node_resizable -t node_state -t node_style -t node_text -t page -t page_metadata -t pgmigrations -t user -s public
 *
 */

export type Json = unknown
export type Direction = 'horizontal' | 'vertical'

// Table language
export interface Language {
  code: string
  id: string
  is_active: boolean
  language: string
}
export interface LanguageInput {
  code: string
  id?: string
  is_active?: boolean
  language: string
}
const language = {
  tableName: 'language',
  columns: ['code', 'id', 'is_active', 'language'],
  requiredForInsert: ['code', 'language'],
  primaryKey: 'id',
  foreignKeys: {},
  $type: null as unknown as Language,
  $input: null as unknown as LanguageInput,
} as const

// Table node
export interface Node {
  class_name: string | null
  created_at: Date
  created_by: string
  css: string | null
  id: string
  is_active: boolean
  language: string
  modified_at: Date | null
  modified_by: string | null
  module_url: string | null
  mount_id: string | null
  /** Friendly name to represent node in CMS */
  name: string | null
  order: number
  page_id: string
  require_auth: boolean
  tag_name: string
  /** hashtag tags for node */
  tags: string[]
}
export interface NodeInput {
  class_name?: string | null
  created_at?: Date
  created_by: string
  css?: string | null
  id?: string
  is_active?: boolean
  language: string
  modified_at?: Date | null
  modified_by?: string | null
  module_url?: string | null
  mount_id?: string | null
  /** Friendly name to represent node in CMS */
  name?: string | null
  order?: number
  page_id: string
  require_auth?: boolean
  tag_name?: string
  /** hashtag tags for node */
  tags?: string[]
}
const node = {
  tableName: 'node',
  columns: [
    'class_name',
    'created_at',
    'created_by',
    'css',
    'id',
    'is_active',
    'language',
    'modified_at',
    'modified_by',
    'module_url',
    'mount_id',
    'name',
    'order',
    'page_id',
    'require_auth',
    'tag_name',
    'tags',
  ],
  requiredForInsert: ['created_by', 'language', 'page_id'],
  primaryKey: 'id',
  foreignKeys: {
    language: {
      table: 'language',
      column: 'id',
      $type: null as unknown as Language,
    },
    mount_id: { table: 'node', column: 'id', $type: null as unknown as Node },
    page_id: { table: 'page', column: 'id', $type: null as unknown as Page },
  },
  $type: null as unknown as Node,
  $input: null as unknown as NodeInput,
} as const

// Table node_attribute
export interface NodeAttribute {
  id: string
  key: string
  node_id: string
  value: string | null
}
export interface NodeAttributeInput {
  id?: string
  key: string
  node_id: string
  value?: string | null
}
const node_attribute = {
  tableName: 'node_attribute',
  columns: ['id', 'key', 'node_id', 'value'],
  requiredForInsert: ['key', 'node_id'],
  primaryKey: 'id',
  foreignKeys: {
    node_id: { table: 'node', column: 'id', $type: null as unknown as Node },
  },
  $type: null as unknown as NodeAttribute,
  $input: null as unknown as NodeAttributeInput,
} as const

// Table node_data_api
export interface NodeDataApi {
  api: string
  id: string
  node_id: string
}
export interface NodeDataApiInput {
  api: string
  id?: string
  node_id: string
}
const node_data_api = {
  tableName: 'node_data_api',
  columns: ['api', 'id', 'node_id'],
  requiredForInsert: ['api', 'node_id'],
  primaryKey: 'id',
  foreignKeys: {
    node_id: { table: 'node', column: 'id', $type: null as unknown as Node },
  },
  $type: null as unknown as NodeDataApi,
  $input: null as unknown as NodeDataApiInput,
} as const

// Table node_data_binding
export interface NodeDataBinding {
  id: string
  key: string
  node_id: string
}
export interface NodeDataBindingInput {
  id?: string
  key: string
  node_id: string
}
const node_data_binding = {
  tableName: 'node_data_binding',
  columns: ['id', 'key', 'node_id'],
  requiredForInsert: ['key', 'node_id'],
  primaryKey: 'id',
  foreignKeys: {
    node_id: { table: 'node', column: 'id', $type: null as unknown as Node },
  },
  $type: null as unknown as NodeDataBinding,
  $input: null as unknown as NodeDataBindingInput,
} as const

// Table node_plugin
export interface NodePlugin {
  cascade_depth: number | null
  id: string
  is_active: boolean
  node_id: string
  order: number
  require_auth: boolean
  show_on_site: boolean
  url: string
}
export interface NodePluginInput {
  cascade_depth?: number | null
  id?: string
  is_active?: boolean
  node_id: string
  order: number
  require_auth?: boolean
  show_on_site?: boolean
  url: string
}
const node_plugin = {
  tableName: 'node_plugin',
  columns: [
    'cascade_depth',
    'id',
    'is_active',
    'node_id',
    'order',
    'require_auth',
    'show_on_site',
    'url',
  ],
  requiredForInsert: ['node_id', 'order', 'url'],
  primaryKey: 'id',
  foreignKeys: {
    node_id: { table: 'node', column: 'id', $type: null as unknown as Node },
  },
  $type: null as unknown as NodePlugin,
  $input: null as unknown as NodePluginInput,
} as const

// Table node_resizable
export interface NodeResizable {
  direction: Direction
  id: string
  node_id: string
  show_on_site: boolean
  size: number[]
}
export interface NodeResizableInput {
  direction: Direction
  id?: string
  node_id: string
  show_on_site?: boolean
  size?: number[]
}
const node_resizable = {
  tableName: 'node_resizable',
  columns: ['direction', 'id', 'node_id', 'show_on_site', 'size'],
  requiredForInsert: ['direction', 'node_id'],
  primaryKey: 'id',
  foreignKeys: {
    node_id: { table: 'node', column: 'id', $type: null as unknown as Node },
  },
  $type: null as unknown as NodeResizable,
  $input: null as unknown as NodeResizableInput,
} as const

// Table node_state
export interface NodeState {
  id: string
  name: string
  node_id: string
  value: Json | null
}
export interface NodeStateInput {
  id?: string
  name: string
  node_id: string
  value?: Json | null
}
const node_state = {
  tableName: 'node_state',
  columns: ['id', 'name', 'node_id', 'value'],
  requiredForInsert: ['name', 'node_id'],
  primaryKey: 'id',
  foreignKeys: {
    node_id: { table: 'node', column: 'id', $type: null as unknown as Node },
  },
  $type: null as unknown as NodeState,
  $input: null as unknown as NodeStateInput,
} as const

// Table node_style
export interface NodeStyle {
  id: string
  key: string
  node_id: string
  value: string | null
}
export interface NodeStyleInput {
  id?: string
  key: string
  node_id: string
  value?: string | null
}
const node_style = {
  tableName: 'node_style',
  columns: ['id', 'key', 'node_id', 'value'],
  requiredForInsert: ['key', 'node_id'],
  primaryKey: 'id',
  foreignKeys: {
    node_id: { table: 'node', column: 'id', $type: null as unknown as Node },
  },
  $type: null as unknown as NodeStyle,
  $input: null as unknown as NodeStyleInput,
} as const

// Table node_text
export interface NodeText {
  id: string
  language: string
  node_id: string
  text: string
}
export interface NodeTextInput {
  id?: string
  language: string
  node_id: string
  text: string
}
const node_text = {
  tableName: 'node_text',
  columns: ['id', 'language', 'node_id', 'text'],
  requiredForInsert: ['language', 'node_id', 'text'],
  primaryKey: 'id',
  foreignKeys: {
    language: {
      table: 'language',
      column: 'id',
      $type: null as unknown as Language,
    },
    node_id: { table: 'node', column: 'id', $type: null as unknown as Node },
  },
  $type: null as unknown as NodeText,
  $input: null as unknown as NodeTextInput,
} as const

// Table page
export interface Page {
  created_at: Date
  created_by: string
  id: string
  is_active: boolean
  language: string | null
  modified_at: Date | null
  modified_by: string | null
  /** Friendly name to represent page in CMS */
  name: string | null
  path: string | null
  require_auth: boolean
  /** hashtag tags for page */
  tags: string[] | null
  title: string | null
}
export interface PageInput {
  created_at?: Date
  created_by: string
  id?: string
  is_active?: boolean
  language?: string | null
  modified_at?: Date | null
  modified_by?: string | null
  /** Friendly name to represent page in CMS */
  name?: string | null
  path?: string | null
  require_auth?: boolean
  /** hashtag tags for page */
  tags?: string[] | null
  title?: string | null
}
const page = {
  tableName: 'page',
  columns: [
    'created_at',
    'created_by',
    'id',
    'is_active',
    'language',
    'modified_at',
    'modified_by',
    'name',
    'path',
    'require_auth',
    'tags',
    'title',
  ],
  requiredForInsert: ['created_by'],
  primaryKey: 'id',
  foreignKeys: {
    language: {
      table: 'language',
      column: 'id',
      $type: null as unknown as Language,
    },
  },
  $type: null as unknown as Page,
  $input: null as unknown as PageInput,
} as const

// Table page_metadata
export interface PageMetadata {
  content: string
  id: string
  is_active: boolean
  name: string
  page_id: string
}
export interface PageMetadataInput {
  content?: string
  id?: string
  is_active?: boolean
  name: string
  page_id: string
}
const page_metadata = {
  tableName: 'page_metadata',
  columns: ['content', 'id', 'is_active', 'name', 'page_id'],
  requiredForInsert: ['name', 'page_id'],
  primaryKey: 'id',
  foreignKeys: {
    page_id: { table: 'page', column: 'id', $type: null as unknown as Page },
  },
  $type: null as unknown as PageMetadata,
  $input: null as unknown as PageMetadataInput,
} as const

// Table pgmigrations
export interface Pgmigrations {
  id: number
  name: string
  run_on: Date
}
export interface PgmigrationsInput {
  id?: number
  name: string
  run_on: Date
}
const pgmigrations = {
  tableName: 'pgmigrations',
  columns: ['id', 'name', 'run_on'],
  requiredForInsert: ['name', 'run_on'],
  primaryKey: 'id',
  foreignKeys: {},
  $type: null as unknown as Pgmigrations,
  $input: null as unknown as PgmigrationsInput,
} as const

// Table user
export interface User {
  alias: string | null
  cms_access: boolean
  first_name: string
  id: string
  last_name: string
  middle_name: string | null
  profile_image: string | null
  role: string
}
export interface UserInput {
  alias?: string | null
  cms_access?: boolean
  first_name?: string
  id: string
  last_name?: string
  middle_name?: string | null
  profile_image?: string | null
  role: string
}
const user = {
  tableName: 'user',
  columns: [
    'alias',
    'cms_access',
    'first_name',
    'id',
    'last_name',
    'middle_name',
    'profile_image',
    'role',
  ],
  requiredForInsert: ['id', 'role'],
  primaryKey: 'id',
  foreignKeys: {},
  $type: null as unknown as User,
  $input: null as unknown as UserInput,
} as const

export interface TableTypes {
  language: {
    select: Language
    input: LanguageInput
  }
  node: {
    select: Node
    input: NodeInput
  }
  node_attribute: {
    select: NodeAttribute
    input: NodeAttributeInput
  }
  node_data_api: {
    select: NodeDataApi
    input: NodeDataApiInput
  }
  node_data_binding: {
    select: NodeDataBinding
    input: NodeDataBindingInput
  }
  node_plugin: {
    select: NodePlugin
    input: NodePluginInput
  }
  node_resizable: {
    select: NodeResizable
    input: NodeResizableInput
  }
  node_state: {
    select: NodeState
    input: NodeStateInput
  }
  node_style: {
    select: NodeStyle
    input: NodeStyleInput
  }
  node_text: {
    select: NodeText
    input: NodeTextInput
  }
  page: {
    select: Page
    input: PageInput
  }
  page_metadata: {
    select: PageMetadata
    input: PageMetadataInput
  }
  pgmigrations: {
    select: Pgmigrations
    input: PgmigrationsInput
  }
  user: {
    select: User
    input: UserInput
  }
}

export const tables = {
  language,
  node,
  node_attribute,
  node_data_api,
  node_data_binding,
  node_plugin,
  node_resizable,
  node_state,
  node_style,
  node_text,
  page,
  page_metadata,
  pgmigrations,
  user,
}
